### ISSUE TITLE
React QR Code Scan Library

### ISSUE THREAD

**Issue by BohdanBed** [DripMicro/HTML_QR_SCAN_TEST#1]
HI, DripMicro

How are you?

Which Library do you used for scan?

Best

**Comment by NebulaNode0728** [comment]
Hi Bohdan 
How are you?
I used [react-qr-reader](https://www.npmjs.com/package/react-qr-reader).
I hope this help you.

**Comment by BohdanBed** [comment]
Thank you for your fast respond
Ok. got it.

**Comment by NebulaNode0728** [comment]
Ok. Happy Coding
